"""
fetch_github_issues.py — Paginate through GitHub Issues and export them to CSV.

This is a sample web/API script generated by Copilot Script Agent.
It demonstrates: API pagination with rate-limit handling, tqdm progress,
--dry-run support, and secrets loaded from environment variables.
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
import time
from pathlib import Path

# Ensure the repository root is on sys.path when this script is run directly.
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

import requests
from tqdm import tqdm

from scripts.common.logger import get_logger
from scripts.common.config import get_env

log = get_logger(__name__)

GITHUB_API = "https://api.github.com"
ISSUES_FIELDS = ["number", "title", "state", "created_at", "updated_at", "html_url", "user"]

# GitHub owner/repo names: alphanumerics plus '-', '_' and '.' only.
SLUG_RE = re.compile(r"^[A-Za-z0-9._-]+$")


def _headers(token: str | None) -> dict[str, str]:
    h = {"Accept": "application/vnd.github+json"}
    if token:
        h["Authorization"] = f"Bearer {token}"
    return h


def fetch_issues(
    owner: str,
    repo: str,
    token: str | None,
    *,
    state: str = "all",
    per_page: int = 100,
) -> list[dict]:
    """Fetch all issues from *owner/repo* using pagination."""
    for label, value in (("owner", owner), ("repo", repo)):
        if not SLUG_RE.match(value):
            raise ValueError(f"Invalid GitHub {label} name: {value!r}")

    url = f"{GITHUB_API}/repos/{owner}/{repo}/issues"
    params: dict = {"state": state, "per_page": per_page, "page": 1}
    all_issues: list[dict] = []

    with tqdm(desc="Fetching issues", unit="page") as bar:
        while True:
            resp = requests.get(url, headers=_headers(token), params=params, timeout=30)
            _handle_rate_limit(resp)
            resp.raise_for_status()
            page = resp.json()
            if not page:
                break
            all_issues.extend(page)
            bar.update(1)
            params["page"] += 1

    log.info("Fetched %d issue(s) from %s/%s.", len(all_issues), owner, repo)
    return all_issues


def _handle_rate_limit(resp: requests.Response) -> None:
    remaining = int(resp.headers.get("X-RateLimit-Remaining", 1))
    if remaining == 0:
        reset = int(resp.headers.get("X-RateLimit-Reset", time.time() + 60))
        wait = max(0, reset - int(time.time())) + 1
        log.warning("Rate limit hit; sleeping %ds.", wait)
        time.sleep(wait)


def issues_to_rows(issues: list[dict]) -> list[dict[str, str]]:
    rows = []
    for issue in issues:
        rows.append({
            "number": str(issue.get("number", "")),
            "title": issue.get("title", ""),
            "state": issue.get("state", ""),
            "created_at": issue.get("created_at", ""),
            "updated_at": issue.get("updated_at", ""),
            "html_url": issue.get("html_url", ""),
            "user": (issue.get("user") or {}).get("login", ""),
        })
    return rows


def main(args: argparse.Namespace) -> int:
    log.info(
        "fetch_github_issues starting (repo=%s/%s, dry_run=%s)",
        args.owner,
        args.repo,
        args.dry_run,
    )

    token = resolve_token(args.token)
    issues = fetch_issues(args.owner, args.repo, token, state=args.state)
    rows = issues_to_rows(issues)
    output = Path(args.output)

    if args.dry_run:
        log.info("[dry-run] Would write %d row(s) to '%s'.", len(rows), output)
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=ISSUES_FIELDS)
        writer.writeheader()
        writer.writerows(rows)
    log.info("Wrote %d issue(s) to '%s'.", len(rows), output)
    return 0


def resolve_token(cli_token: str | None) -> str | None:
    """Return the GitHub token, preferring ``GITHUB_TOKEN`` over the CLI flag.

    Tokens passed on the command line are visible to any process on the host
    (via the process table) and are recorded in shell history, so ``--token``
    is accepted only with a warning.
    """
    if cli_token:
        log.warning(
            "Passing a token via --token exposes it in the process list and "
            "shell history; prefer the GITHUB_TOKEN environment variable."
        )
        return cli_token
    return get_env("GITHUB_TOKEN") or None


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fetch GitHub Issues for a repository and export to CSV."
    )
    parser.add_argument("owner", help="Repository owner (user or org).")
    parser.add_argument("repo", help="Repository name.")
    parser.add_argument("--output", default="issues.csv", help="Output CSV path.")
    parser.add_argument("--state", default="all", choices=["open", "closed", "all"])
    parser.add_argument(
        "--token",
        default=None,
        help=(
            "GitHub personal access token.  Prefer the GITHUB_TOKEN env var: "
            "tokens given here are visible in the process list."
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=False,
        help="Show what would be done without writing files.",
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    sys.exit(main(parse_args()))
