"""
fetch_github_issues.py — Paginate through GitHub Issues and export them to CSV.

This is a sample web/API script generated by Copilot Script Agent.
It demonstrates: API pagination with rate-limit handling, tqdm progress,
--dry-run support, and secrets loaded from environment variables.
"""

from __future__ import annotations

import argparse
import csv
import os
import sys
import time
from pathlib import Path

# Ensure the repository root is on sys.path when this script is run directly.
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

import requests
from tqdm import tqdm

from scripts.common.logger import get_logger

log = get_logger(__name__)

GITHUB_API = "https://api.github.com"
ISSUES_FIELDS = ["number", "title", "state", "created_at", "updated_at", "html_url", "user"]


def _headers(token: str | None) -> dict[str, str]:
    h = {"Accept": "application/vnd.github+json"}
    if token:
        h["Authorization"] = f"Bearer {token}"
    return h


def fetch_issues(
    owner: str,
    repo: str,
    token: str | None,
    *,
    state: str = "all",
    per_page: int = 100,
) -> list[dict]:
    """Fetch all issues from *owner/repo* using pagination."""
    url = f"{GITHUB_API}/repos/{owner}/{repo}/issues"
    params: dict = {"state": state, "per_page": per_page, "page": 1}
    all_issues: list[dict] = []

    with tqdm(desc="Fetching issues", unit="page") as bar:
        while True:
            resp = _get_with_rate_limit_retry(url, token, params)
            resp.raise_for_status()
            try:
                page = resp.json()
            except ValueError as exc:
                raise requests.exceptions.InvalidJSONError(
                    f"GitHub returned a non-JSON response for page "
                    f"{params['page']}: {resp.text[:200]!r}"
                ) from exc
            if not isinstance(page, list):
                raise requests.exceptions.InvalidJSONError(
                    f"Expected a JSON array of issues, got {type(page).__name__}: "
                    f"{page!r:.200}"
                )
            if not page:
                break
            all_issues.extend(page)
            bar.update(1)
            params["page"] += 1

    log.info("Fetched %d issue(s) from %s/%s.", len(all_issues), owner, repo)
    return all_issues


def _get_with_rate_limit_retry(
    url: str,
    token: str | None,
    params: dict,
    *,
    max_retries: int = 3,
) -> requests.Response:
    """GET *url*, waiting out rate limits and retrying up to *max_retries* times."""
    for attempt in range(1, max_retries + 1):
        resp = requests.get(url, headers=_headers(token), params=params, timeout=30)
        wait = _rate_limit_wait(resp)
        if wait is None or attempt == max_retries:
            return resp
        log.warning(
            "Rate limit hit on page %s; sleeping %ds (attempt %d/%d).",
            params.get("page"),
            wait,
            attempt,
            max_retries,
        )
        time.sleep(wait)
    raise AssertionError("unreachable")  # pragma: no cover


def _rate_limit_wait(resp: requests.Response) -> int | None:
    """Return seconds to wait if *resp* was rate limited, else ``None``."""
    remaining = _header_int(resp, "X-RateLimit-Remaining", 1)
    if remaining != 0:
        return None
    reset = _header_int(resp, "X-RateLimit-Reset", int(time.time()) + 60)
    return max(0, reset - int(time.time())) + 1


def _header_int(resp: requests.Response, name: str, default: int) -> int:
    """Return header *name* as an int, falling back to *default* when malformed."""
    raw = resp.headers.get(name)
    if raw is None:
        return default
    try:
        return int(raw)
    except ValueError:
        log.warning("Ignoring malformed %s header: %r", name, raw)
        return default


def issues_to_rows(issues: list[dict]) -> list[dict[str, str]]:
    rows = []
    for issue in issues:
        rows.append({
            "number": str(issue.get("number", "")),
            "title": issue.get("title", ""),
            "state": issue.get("state", ""),
            "created_at": issue.get("created_at", ""),
            "updated_at": issue.get("updated_at", ""),
            "html_url": issue.get("html_url", ""),
            "user": (issue.get("user") or {}).get("login", ""),
        })
    return rows


def main(args: argparse.Namespace) -> int:
    log.info(
        "fetch_github_issues starting (repo=%s/%s, dry_run=%s)",
        args.owner,
        args.repo,
        args.dry_run,
    )

    token = args.token or os.environ.get("GITHUB_TOKEN")
    try:
        issues = fetch_issues(args.owner, args.repo, token, state=args.state)
    except requests.RequestException as exc:
        log.error("Failed to fetch issues for %s/%s: %s", args.owner, args.repo, exc)
        return 1

    rows = issues_to_rows(issues)
    output = Path(args.output)

    if args.dry_run:
        log.info("[dry-run] Would write %d row(s) to '%s'.", len(rows), output)
        return 0

    try:
        output.parent.mkdir(parents=True, exist_ok=True)
        with output.open("w", encoding="utf-8", newline="") as fh:
            writer = csv.DictWriter(fh, fieldnames=ISSUES_FIELDS)
            writer.writeheader()
            writer.writerows(rows)
    except (OSError, csv.Error) as exc:
        log.error("Failed to write CSV to '%s': %s", output, exc)
        return 1
    log.info("Wrote %d issue(s) to '%s'.", len(rows), output)
    return 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fetch GitHub Issues for a repository and export to CSV."
    )
    parser.add_argument("owner", help="Repository owner (user or org).")
    parser.add_argument("repo", help="Repository name.")
    parser.add_argument("--output", default="issues.csv", help="Output CSV path.")
    parser.add_argument("--state", default="all", choices=["open", "closed", "all"])
    parser.add_argument(
        "--token",
        default=None,
        help="GitHub personal access token (or set GITHUB_TOKEN env var).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=False,
        help="Show what would be done without writing files.",
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    sys.exit(main(parse_args()))
