"""
fetch_github_issues.py — Paginate through GitHub Issues and export them to CSV.

This is a sample web/API script generated by Copilot Script Agent.
It demonstrates: API pagination with rate-limit handling, tqdm progress,
--dry-run support, and secrets loaded from environment variables.
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

# Ensure the repository root is on sys.path when this script is run directly.
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import requests
from tqdm import tqdm

from scripts.common.cli import build_parser, log_start, run
from scripts.common.csv_ops import write_csv
from scripts.common.logger import get_logger

log = get_logger(__name__)

GITHUB_API = "https://api.github.com"
ISSUES_FIELDS = ["number", "title", "state", "created_at", "updated_at", "html_url", "user"]


def _headers(token: str | None) -> dict[str, str]:
    h = {"Accept": "application/vnd.github+json"}
    if token:
        h["Authorization"] = f"Bearer {token}"
    return h


def fetch_issues(
    owner: str,
    repo: str,
    token: str | None,
    *,
    state: str = "all",
    per_page: int = 100,
) -> list[dict]:
    """Fetch all issues from *owner/repo* using pagination."""
    url = f"{GITHUB_API}/repos/{owner}/{repo}/issues"
    params: dict = {"state": state, "per_page": per_page, "page": 1}
    all_issues: list[dict] = []

    with tqdm(desc="Fetching issues", unit="page") as bar:
        while True:
            resp = requests.get(url, headers=_headers(token), params=params, timeout=30)
            _handle_rate_limit(resp)
            resp.raise_for_status()
            page = resp.json()
            if not page:
                break
            all_issues.extend(page)
            bar.update(1)
            params["page"] += 1

    log.info("Fetched %d issue(s) from %s/%s.", len(all_issues), owner, repo)
    return all_issues


def _handle_rate_limit(resp: requests.Response) -> None:
    remaining = int(resp.headers.get("X-RateLimit-Remaining", 1))
    if remaining == 0:
        reset = int(resp.headers.get("X-RateLimit-Reset", time.time() + 60))
        wait = max(0, reset - int(time.time())) + 1
        log.warning("Rate limit hit; sleeping %ds.", wait)
        time.sleep(wait)


def issues_to_rows(issues: list[dict]) -> list[dict[str, str]]:
    rows = []
    for issue in issues:
        rows.append({
            "number": str(issue.get("number", "")),
            "title": issue.get("title", ""),
            "state": issue.get("state", ""),
            "created_at": issue.get("created_at", ""),
            "updated_at": issue.get("updated_at", ""),
            "html_url": issue.get("html_url", ""),
            "user": (issue.get("user") or {}).get("login", ""),
        })
    return rows


def main(args: argparse.Namespace) -> int:
    log_start(
        "fetch_github_issues",
        repo=f"{args.owner}/{args.repo}",
        dry_run=args.dry_run,
    )

    issues = fetch_issues(args.owner, args.repo, args.token, state=args.state)
    rows = issues_to_rows(issues)
    write_csv(Path(args.output), ISSUES_FIELDS, rows, dry_run=args.dry_run)
    return 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = build_parser("Fetch GitHub Issues for a repository and export to CSV.")
    parser.add_argument("owner", help="Repository owner (user or org).")
    parser.add_argument("repo", help="Repository name.")
    parser.add_argument("--output", default="issues.csv", help="Output CSV path.")
    parser.add_argument("--state", default="all", choices=["open", "closed", "all"])
    parser.add_argument(
        "--token",
        default=None,
        help="GitHub personal access token (or set GITHUB_TOKEN env var).",
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    run(main, parse_args)
