"""
invoice_total.py — Calculate the total for an invoice from line items.

This is a sample data-processing script generated by Copilot Script Agent.
It demonstrates: CSV-based input, decimal arithmetic for money, tqdm progress
bars, --dry-run support, and structured logging.

Line items are read from a CSV with the columns:
    description, quantity, unit_price

Example CSV (items.csv)
-----------------------
    description,quantity,unit_price
    Web design,3,100.00
    Hosting,1,50.00
    Support,2,25.00

Usage
-----
    python scripts/data_processing/invoice_total.py --input items.csv
    python scripts/data_processing/invoice_total.py --input items.csv --output invoice.txt
    python scripts/data_processing/invoice_total.py --input items.csv --dry-run
"""

from __future__ import annotations

import argparse
import csv
import sys
from decimal import Decimal, InvalidOperation, ROUND_HALF_UP
from pathlib import Path

# Ensure the repository root is on sys.path when this script is run directly.
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from tqdm import tqdm

from scripts.common.logger import get_logger
from scripts.common.file_ops import safe_write

log = get_logger(__name__)

_CENT = Decimal("0.01")


def load_items(path: Path) -> list[dict[str, str]]:
    """Read line items from *path* and return a list of raw row dicts."""
    with path.open(encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        rows = list(reader)
    log.info("Loaded %d line item(s) from '%s'.", len(rows), path)
    return rows


def compute_totals(
    rows: list[dict[str, str]],
) -> tuple[list[dict[str, Decimal | str]], Decimal]:
    """Return (enriched_rows, invoice_total).

    Each enriched row gains a ``line_total`` key (quantity × unit_price).
    Missing or invalid numeric fields are treated as zero with a warning.
    """
    enriched: list[dict[str, Decimal | str]] = []
    invoice_total = Decimal("0")

    for row in tqdm(rows, desc="Computing totals", unit="item"):
        description = row.get("description", "").strip()
        try:
            quantity = Decimal(str(row.get("quantity", "0")).strip())
        except InvalidOperation:
            log.warning("Invalid quantity for '%s'; using 0.", description)
            quantity = Decimal("0")
        try:
            unit_price = Decimal(str(row.get("unit_price", "0")).strip())
        except InvalidOperation:
            log.warning("Invalid unit_price for '%s'; using 0.", description)
            unit_price = Decimal("0")

        line_total = (quantity * unit_price).quantize(_CENT, rounding=ROUND_HALF_UP)
        invoice_total += line_total

        enriched.append({
            "description": description,
            "quantity": quantity,
            "unit_price": unit_price,
            "line_total": line_total,
        })

    invoice_total = invoice_total.quantize(_CENT, rounding=ROUND_HALF_UP)
    return enriched, invoice_total


def format_invoice(
    enriched: list[dict[str, Decimal | str]],
    invoice_total: Decimal,
) -> str:
    """Return a formatted plain-text invoice report."""
    col_w = 30
    lines = [
        "Invoice",
        "=======",
        f"{'Description':<{col_w}} {'Qty':>6}  {'Unit Price':>10}  {'Line Total':>10}",
        "-" * (col_w + 32),
    ]
    for item in enriched:
        lines.append(
            f"{str(item['description']):<{col_w}} "
            f"{item['quantity']:>6}  "
            f"${item['unit_price']:>9.2f}  "
            f"${item['line_total']:>9.2f}"
        )
    lines += [
        "-" * (col_w + 32),
        f"Invoice Total: ${f'{invoice_total:.2f}'.rstrip('0').rstrip('.')}",
    ]
    return "\n".join(lines)


def main(args: argparse.Namespace) -> int:
    log.info("invoice_total starting (input=%s, dry_run=%s)", args.input, args.dry_run)

    input_path = Path(args.input)
    if not input_path.exists():
        log.error("Input file '%s' not found.", input_path)
        return 1

    rows = load_items(input_path)
    if not rows:
        log.warning("No line items found in '%s'.", input_path)
        return 0

    enriched, invoice_total = compute_totals(rows)
    report = format_invoice(enriched, invoice_total)

    print(report)

    if args.output:
        safe_write(Path(args.output), report, dry_run=args.dry_run)

    return 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Calculate the total for an invoice from CSV line items."
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Path to the input CSV file (columns: description, quantity, unit_price).",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Optional path to write the plain-text invoice report.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=False,
        help="Show what would be done without writing files.",
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    sys.exit(main(parse_args()))
