"""
merge_csvs.py — Merge multiple CSV files, normalize headers, and produce a summary report.

This is a sample data-processing script generated by Copilot Script Agent.
It demonstrates: pandas-free CSV merging using stdlib csv, tqdm progress bars,
--dry-run support, and structured logging.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Ensure the repository root is on sys.path when this script is run directly.
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from tqdm import tqdm

from scripts.common.cli import build_parser, log_start, run
from scripts.common.csv_ops import normalize_header, read_csv, write_csv
from scripts.common.file_ops import safe_write
from scripts.common.logger import get_logger

log = get_logger(__name__)


def merge_csvs(input_paths: list[Path]) -> tuple[list[str], list[dict[str, str]]]:
    """Merge CSV files and return (unified_headers, rows)."""
    all_rows: list[dict[str, str]] = []
    all_headers: list[str] = []

    for path in tqdm(input_paths, desc="Reading CSVs", unit="file"):
        fieldnames, rows = read_csv(path)
        if not fieldnames:
            log.warning("Skipping '%s': no headers found.", path)
            continue
        norm = normalize_header(fieldnames)
        mapping = dict(zip(fieldnames, norm))
        for row in rows:
            all_rows.append({mapping[k]: v for k, v in row.items()})
        for h in norm:
            if h not in all_headers:
                all_headers.append(h)

    return all_headers, all_rows


def build_summary(headers: list[str], rows: list[dict[str, str]]) -> str:
    """Return a plain-text summary report."""
    lines = [
        f"Summary Report",
        f"==============",
        f"Total rows   : {len(rows)}",
        f"Columns ({len(headers)}): {', '.join(headers)}",
    ]
    return "\n".join(lines)


def main(args: argparse.Namespace) -> int:
    log_start("merge_csvs", dry_run=args.dry_run)

    input_paths = [Path(p) for p in args.inputs]
    missing = [p for p in input_paths if not p.exists()]
    if missing:
        log.error("Files not found: %s", missing)
        return 1

    headers, rows = merge_csvs(input_paths)
    log.info("Merged %d row(s) across %d file(s).", len(rows), len(input_paths))

    # Write merged CSV
    output_path = Path(args.output)
    write_csv(output_path, headers, rows, dry_run=args.dry_run)

    # Write summary report
    summary = build_summary(headers, rows)
    report_path = output_path.with_suffix(".txt")
    safe_write(report_path, summary, dry_run=args.dry_run)

    return 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = build_parser("Merge multiple CSV files and produce a summary.")
    parser.add_argument("inputs", nargs="+", help="Input CSV file paths.")
    parser.add_argument("--output", default="merged.csv", help="Output CSV path (default: merged.csv).")
    return parser.parse_args(argv)


if __name__ == "__main__":
    run(main, parse_args)
