"""
md_to_text.py — Convert Markdown files to plain text with a progress bar.

This is a sample utilities script generated by Copilot Script Agent.
It demonstrates: batch file conversion, tqdm progress bars,
--dry-run support, and structured logging.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Ensure the repository root is on sys.path when this script is run directly.
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from tqdm import tqdm

from scripts.common.logger import get_logger
from scripts.common.file_ops import safe_write

log = get_logger(__name__)


def md_to_text(md: str) -> str:
    """Strip common Markdown syntax and return plain text."""
    # Remove fenced code blocks
    text = re.sub(r"```[^\n]*\n.*?```", "", md, flags=re.DOTALL)
    # Remove inline code
    text = re.sub(r"`[^`]+`", lambda m: m.group(0)[1:-1], text)
    # Remove headings
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.MULTILINE)
    # Remove bold/italic
    text = re.sub(r"\*{1,2}([^*]+)\*{1,2}", r"\1", text)
    text = re.sub(r"_{1,2}([^_]+)_{1,2}", r"\1", text)
    # Remove links, keep text
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    # Remove images
    text = re.sub(r"!\[[^\]]*\]\([^)]+\)", "", text)
    # Remove horizontal rules
    text = re.sub(r"^[-*_]{3,}\s*$", "", text, flags=re.MULTILINE)
    # Collapse blank lines
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def convert_files(
    input_paths: list[Path],
    output_dir: Path,
    *,
    dry_run: bool,
) -> int:
    """Convert *input_paths* to plain text in *output_dir*."""
    converted = 0
    for src in tqdm(input_paths, desc="Converting", unit="file"):
        dest = output_dir / src.with_suffix(".txt").name
        md = src.read_text(encoding="utf-8")
        plain = md_to_text(md)
        safe_write(dest, plain, dry_run=dry_run)
        converted += 1
    return converted


def main(args: argparse.Namespace) -> int:
    log.info("md_to_text starting (dry_run=%s)", args.dry_run)

    input_paths = list(Path(args.input_dir).rglob("*.md"))
    if not input_paths:
        log.warning("No Markdown files found in '%s'.", args.input_dir)
        return 0

    log.info("Found %d Markdown file(s).", len(input_paths))
    output_dir = Path(args.output_dir)
    count = convert_files(input_paths, output_dir, dry_run=args.dry_run)
    log.info("Converted %d file(s).", count)
    return 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert Markdown files to plain text."
    )
    parser.add_argument("--input-dir", default=".", help="Directory to scan for .md files.")
    parser.add_argument("--output-dir", default="./output", help="Destination directory for .txt files.")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=False,
        help="Show what would be done without writing files.",
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    sys.exit(main(parse_args()))
