"""
archive_old_logs.py — Archive log files older than N days to a backup folder.

This is a sample system-automation script generated by Copilot Script Agent.
It demonstrates the standard script template: main(), argparse with --dry-run,
structured logging, and tqdm progress bars.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from datetime import datetime, timedelta
from pathlib import Path

# Ensure the repository root is on sys.path when this script is run directly.
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from tqdm import tqdm

from scripts.common.logger import get_logger

log = get_logger(__name__)


def find_old_logs(log_dir: Path, days: int) -> list[Path]:
    """Return log files in *log_dir* older than *days* days."""
    cutoff = datetime.now() - timedelta(days=days)
    return [
        p for p in log_dir.rglob("*.log")
        if datetime.fromtimestamp(p.stat().st_mtime) < cutoff
    ]


def archive_logs(
    files: list[Path],
    backup_dir: Path,
    *,
    dry_run: bool,
) -> int:
    """Copy *files* to *backup_dir*.  Returns the number of files archived."""
    archived = 0
    for src in tqdm(files, desc="Archiving logs", unit="file"):
        dest = backup_dir / src.name
        if dry_run:
            log.info("[dry-run] Would archive '%s' → '%s'.", src, dest)
        else:
            backup_dir.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dest)
            log.info("Archived '%s' → '%s'.", src, dest)
        archived += 1
    return archived


def main(args: argparse.Namespace) -> int:
    log.info(
        "archive_old_logs starting (log_dir=%s, days=%d, dry_run=%s)",
        args.log_dir,
        args.days,
        args.dry_run,
    )

    log_dir = Path(args.log_dir)
    if not log_dir.exists():
        log.error("Log directory '%s' does not exist.", log_dir)
        return 1

    old_files = find_old_logs(log_dir, args.days)
    log.info("Found %d log file(s) older than %d day(s).", len(old_files), args.days)

    if not old_files:
        log.info("Nothing to archive.")
        return 0

    backup_dir = Path(args.backup_dir)
    count = archive_logs(old_files, backup_dir, dry_run=args.dry_run)
    log.info("Archived %d file(s).", count)
    return 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Archive log files older than N days to a backup folder."
    )
    parser.add_argument("--log-dir", default="/var/log", help="Directory to scan.")
    parser.add_argument("--backup-dir", default="/var/log/archive", help="Backup destination.")
    parser.add_argument("--days", type=int, default=30, help="Age threshold in days (default: 30).")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=False,
        help="Show what would be done without making changes.",
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    sys.exit(main(parse_args()))
